
jobs:
  build:
    docker:
      -image: circleci/openjdk:11.0.1-jdk

      steps:
        -checkout

       -run: mvn clean package
       -run: mvn clean compile jib:build -Djib.to.auth.username=$DOCKER_USER -Djib.to.auth.password=$DOCKER_PASS -Dimage=ElmiraPiriyeva/calctest:$CIRCLE_BUILD_NUM